spring:
  application:
    name: search
  profiles:
    active: local
  main:
    web-application-type: reactive
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 开启请求方式前缀
server:
  port: 8082
